# golangci-lint configuration for Axon

run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: axon
  
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - misspell
    - gofmt
    - goimports
  
  disable-all: false
  fast: false

issues:
  exclude-dirs:
    - vendor
    - testdata
    - build
    - dist
  
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  
  max-issues-per-linter: 50
  max-same-issues: 3

