# golangci-lint configuration for Axon
version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - build
    - dist

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/elialdridge/axon
  
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
  disable-all: false
  fast: false

issues:
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_gen\\.go$"
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  
  max-issues-per-linter: 50
  max-same-issues: 3

