name: Documentation

on:
  push:
    branches: [main]
    paths: ['**.md', '**.go']
  pull_request:
    branches: [main]
    paths: ['**.md', '**.go']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - uses: actions/configure-pages@v4
    
    - name: Build docs
      run: |
        mkdir -p _site
        
        # Copy markdown files as HTML
        for file in README.md DOCUMENTATION.md CONTRIBUTING.md; do
          if [[ -f "$file" ]]; then
            name=$(basename "$file" .md | tr '[:upper:]' '[:lower:]')
            [[ "$name" == "readme" ]] && name="index"
            
            cat > "_site/${name}.html" << EOF
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>$(basename "$file" .md) - Axon</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }
                pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
                code { background: #f6f8fa; padding: 0.2rem 0.4rem; border-radius: 3px; }
                h1, h2, h3 { color: #24292f; }
                a { color: #0969da; }
                nav { margin-bottom: 2rem; padding: 1rem 0; border-bottom: 1px solid #d1d9e0; }
                nav a { margin-right: 1rem; text-decoration: none; }
            </style>
        </head>
        <body>
            <nav>
                <a href="index.html">Home</a>
                <a href="documentation.html">Documentation</a>
                <a href="contributing.html">Contributing</a>
                <a href="api.html">API</a>
            </nav>
            <main>
        EOF
            
            # Convert markdown to basic HTML
            sed 's/^# /\n<h1>/; s/^## /\n<h2>/; s/^### /\n<h3>/; 
                 s/^\* /\n<li>/; s/^- /\n<li>/;
                 s/\[\([^]]*\)\](\([^)]*\))/<a href="\2">\1<\/a>/g;
                 s/`\([^`]*\)`/<code>\1<\/code>/g' "$file" >> "_site/${name}.html"
            
            echo "\n</main>\n</body>\n</html>" >> "_site/${name}.html"
          fi
        done
        
        # Generate API documentation
        if go list ./... >/dev/null 2>&1; then
          cat > _site/api.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>API Documentation - Axon</title>
            <style>
                body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; }
                pre { background: #f6f8fa; padding: 1rem; border-radius: 6px; overflow-x: auto; }
                h1, h2, h3 { color: #24292f; }
                nav { margin-bottom: 2rem; padding: 1rem 0; border-bottom: 1px solid #d1d9e0; }
                nav a { margin-right: 1rem; text-decoration: none; }
            </style>
        </head>
        <body>
            <nav>
                <a href="index.html">Home</a>
                <a href="documentation.html">Documentation</a>
                <a href="contributing.html">Contributing</a>
                <a href="api.html">API</a>
            </nav>
            <main>
                <h1>API Documentation</h1>
        EOF
          
          for pkg in $(go list ./... 2>/dev/null); do
            echo "<h2>Package: $(basename $pkg)</h2>" >> _site/api.html
            echo "<pre>" >> _site/api.html
            go doc "$pkg" 2>/dev/null | sed 's/</\&lt;/g; s/>/\&gt;/g' >> _site/api.html || echo "No documentation available" >> _site/api.html
            echo "</pre>" >> _site/api.html
          done
          
          echo "</main></body></html>" >> _site/api.html
        fi
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: _site
    
    - id: deployment
      uses: actions/deploy-pages@v4

