name: Documentation

on:
  push:
    branches: [main]
    paths: ['**.md', '**.go']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    - uses: actions/configure-pages@v4
    
    - name: Setup Jekyll site
      run: |
        mkdir -p _site
        
        # Use minimal theme from GitHub
        cat > _config.yml << 'EOF'
        theme: minima
        title: Axon
        description: AI-powered text adventure in your terminal
        baseurl: ""
        url: "https://elialdridge.github.io"
        github_username: elialdridge
        
        markdown: kramdown
        highlighter: rouge
        
        plugins:
          - jekyll-feed
          - jekyll-sitemap
        
        header_pages:
          - README.md
          - DOCUMENTATION.md
          - CONTRIBUTING.md
          - api.md
        EOF
        
        # Generate API docs
        echo "---" > api.md
        echo "title: API Reference" >> api.md
        echo "---" >> api.md
        echo "" >> api.md
        echo "# API Reference" >> api.md
        echo "" >> api.md
        
        go list ./... 2>/dev/null | while read pkg; do
          echo "## $(basename $pkg)" >> api.md
          echo "" >> api.md
          echo '```go' >> api.md
          go doc $pkg 2>/dev/null >> api.md || echo "No documentation available"
          echo '```' >> api.md
          echo "" >> api.md
        done
    
    - uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site
    
    - uses: actions/upload-pages-artifact@v3
    
    - uses: actions/deploy-pages@v4

