name: Documentation

on:
  push:
    branches: [main]
    paths: ['**.md', '**.go']
  pull_request:
    branches: [main]
    paths: ['**.md', '**.go']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - uses: actions/configure-pages@v4
    
    - name: Install mdBook
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.40/mdbook-v0.4.40-x86_64-unknown-linux-gnu.tar.gz | tar -xz
        sudo mv mdbook /usr/local/bin/
    
    - name: Setup mdBook project
      run: |
        # Initialize mdBook if not exists
        if [[ ! -f "book.toml" ]]; then
          mdbook init --force .
        fi
        
        # Configure book.toml
        cat > book.toml << 'EOF'
        [book]
        title = "Axon Documentation"
        description = "Complete documentation for the Axon project"
        authors = ["Axon Team"]
        language = "en"
        src = "docs"
        
        [output.html]
        default-theme = "navy"
        preferred-dark-theme = "navy"
        git-repository-url = "https://github.com/elialdridge/axon"
        edit-url-template = "https://github.com/elialdridge/axon/edit/main/{path}"
        
        [output.html.search]
        enable = true
        
        [output.html.print]
        enable = true
        EOF
        
        # Create docs directory structure
        mkdir -p docs
        
        # Create SUMMARY.md for navigation
        cat > docs/SUMMARY.md << 'EOF'
        # Summary
        
        - [Introduction](./README.md)
        - [Documentation](./DOCUMENTATION.md)
        - [Contributing](./CONTRIBUTING.md)
        - [API Reference](./api.md)
        EOF
        
        # Copy existing markdown files to docs/
        cp README.md docs/ 2>/dev/null || echo "# Axon\n\nWelcome to Axon documentation." > docs/README.md
        cp DOCUMENTATION.md docs/ 2>/dev/null || echo "# Documentation\n\nDetailed documentation will be here." > docs/DOCUMENTATION.md
        cp CONTRIBUTING.md docs/ 2>/dev/null || echo "# Contributing\n\nContribution guidelines will be here." > docs/CONTRIBUTING.md
    
    - name: Generate API documentation
      run: |
        cat > docs/api.md << 'EOF'
        # API Reference
        
        This page contains the complete API documentation for all packages in the Axon project.
        
        EOF
        
        if go list ./... >/dev/null 2>&1; then
          for pkg in $(go list ./... 2>/dev/null); do
            pkg_name=$(basename "$pkg")
            echo "## Package: \`$pkg_name\`" >> docs/api.md
            echo "" >> docs/api.md
            echo '```go' >> docs/api.md
            go doc "$pkg" 2>/dev/null >> docs/api.md || echo "No documentation available for this package."
            echo '```' >> docs/api.md
            echo "" >> docs/api.md
          done
        else
          echo "No Go packages found in this project." >> docs/api.md
        fi
    
    - name: Build with mdBook
      run: mdbook build
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: book
    
    - id: deployment
      uses: actions/deploy-pages@v4

