name: Documentation

on:
  push:
    branches: [main]
    paths: ['**.md', '**.go']
  pull_request:
    branches: [main]
    paths: ['**.md', '**.go']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
    
    - uses: actions/configure-pages@v4
    
    - name: Install pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc
    
    - name: Create CSS template
      run: |
        mkdir -p _site
        cat > template.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>$title$ - Axon</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica', 'Arial', sans-serif;
                    max-width: 900px;
                    margin: 0 auto;
                    padding: 2rem;
                    line-height: 1.6;
                    color: #24292f;
                }
                nav {
                    background: #f6f8fa;
                    padding: 1rem;
                    margin: -2rem -2rem 2rem -2rem;
                    border-bottom: 1px solid #d0d7de;
                }
                nav a {
                    color: #0969da;
                    text-decoration: none;
                    margin-right: 1.5rem;
                    font-weight: 500;
                }
                nav a:hover {
                    text-decoration: underline;
                }
                h1, h2, h3, h4, h5, h6 {
                    color: #1f2328;
                    margin-top: 2rem;
                    margin-bottom: 1rem;
                }
                h1 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3rem; }
                h2 { border-bottom: 1px solid #d0d7de; padding-bottom: 0.3rem; }
                pre {
                    background: #f6f8fa;
                    border: 1px solid #d0d7de;
                    border-radius: 6px;
                    padding: 16px;
                    overflow-x: auto;
                    font-size: 85%;
                }
                code {
                    background: rgba(175,184,193,0.2);
                    padding: 0.2em 0.4em;
                    border-radius: 6px;
                    font-size: 85%;
                }
                pre code {
                    background: transparent;
                    padding: 0;
                }
                blockquote {
                    padding: 0 1em;
                    color: #656d76;
                    border-left: 0.25em solid #d0d7de;
                    margin: 0;
                }
                table {
                    border-collapse: collapse;
                    width: 100%;
                    margin: 1rem 0;
                }
                th, td {
                    border: 1px solid #d0d7de;
                    padding: 6px 13px;
                    text-align: left;
                }
                th {
                    background: #f6f8fa;
                    font-weight: 600;
                }
                a {
                    color: #0969da;
                    text-decoration: none;
                }
                a:hover {
                    text-decoration: underline;
                }
                img {
                    max-width: 100%;
                    height: auto;
                }
                .highlight {
                    background: #fff8c5;
                    padding: 0.2em 0.4em;
                    border-radius: 3px;
                }
            </style>
        </head>
        <body>
            <nav>
                <a href="index.html">🏠 Home</a>
                <a href="documentation.html">📚 Documentation</a>
                <a href="contributing.html">🤝 Contributing</a>
                <a href="api.html">⚡ API</a>
            </nav>
            <main>
        $body$
            </main>
        </body>
        </html>
        EOF
    
    - name: Build documentation
      run: |
        # Convert markdown files using pandoc
        for file in README.md DOCUMENTATION.md CONTRIBUTING.md; do
          if [[ -f "$file" ]]; then
            name=$(basename "$file" .md | tr '[:upper:]' '[:lower:]')
            [[ "$name" == "readme" ]] && name="index"
            
            title=$(basename "$file" .md)
            [[ "$title" == "README" ]] && title="Home"
            
            pandoc "$file" \
              --from gfm \
              --to html5 \
              --template template.html \
              --metadata title="$title" \
              --highlight-style pygments \
              --output "_site/${name}.html"
          fi
        done
    
    - name: Generate API documentation
      run: |
        if go list ./... >/dev/null 2>&1; then
          # Create API markdown first
          cat > api.md << 'EOF'
        # API Documentation
        
        This page contains the API documentation for all packages in the Axon project.
        
        EOF
          
          for pkg in $(go list ./... 2>/dev/null); do
            pkg_name=$(basename "$pkg")
            echo "## Package: $pkg_name" >> api.md
            echo "" >> api.md
            echo '```go' >> api.md
            go doc "$pkg" 2>/dev/null >> api.md || echo "No documentation available for this package." >> api.md
            echo '```' >> api.md
            echo "" >> api.md
          done
          
          # Convert API markdown to HTML using pandoc
          pandoc api.md \
            --from gfm \
            --to html5 \
            --template template.html \
            --metadata title="API" \
            --highlight-style pygments \
            --output "_site/api.html"
          
          rm api.md
        else
          # Fallback if no Go packages found
          echo "# API Documentation\n\nNo Go packages found in this project." | \
          pandoc \
            --from gfm \
            --to html5 \
            --template template.html \
            --metadata title="API" \
            --output "_site/api.html"
        fi
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: _site
    
    - id: deployment
      uses: actions/deploy-pages@v4

